fix: adjust for typeError
After upgrading to D11, got a TypeError message when importing config:
```
TypeError: Drupal\ocha_key_figures\Controller\WebhookController::__construct(): Argument #4 ($event_dispatcher) must be of type Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher, Symfony\Component\EventDispatcher\EventDispatcher given, called in /srv/www/html/core/lib/Drupal/Component/DependencyInjection/Container.php on line 259 in Drupal\ocha_key_figures\Controller\WebhookController->__construct() (line 60 of /srv/www/html/modules/contrib/ocha_key_figures/src/Controller/WebhookController.php).
```